name: Test project
# This workflow is triggered on pushes to the repository.
on:
  push:
      branches:
        - master
jobs:
  test-hello:
    name: Test hello-world assigment
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: download-openmpi
        run: wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.2.tar.gz
      - name: extract-openmpi
        run: tar -xvf ./openmpi-4.0.2.tar.gz
      - name: configure-openmpi
        run: ./openmpi-4.0.2/configure --prefix="/home/${USER}/.openmpi"
      - name: install-openmpi
        run: |
          make -j
          sudo make install
      - name: Test hello-world
        run: cd hello && export CC="mpicc" && make && mpiexec -np 4 hello.out
  
      