name: Test project
# This workflow is triggered on pushes to the repository.
on:
  push:
      branches:
        - master
jobs:
  test-hello:
    name: Test hello-world assigment
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc make cmake openmpi
      - name: Test hello-world
        run: cd hello && export CC="mpicc" make && ./hello.out
  
      